add_newline = false

format = '$directory$character'
right_format = '$git_branch$git_status'
continuation_prompt = ""

[character]
success_symbol = '»'
error_symbol = '[»](red)'

[package]
disabled = true

[directory]
style = "yellow"

[git_branch]
format = '[$branch(:$remote_branch)]($style)'

[git_status]
format = '([$all_status$ahead_behind]($style))'
untracked = "*"
modified = "*"
staged = "*"
renamed = "*"
deleted = "*"
