export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

export ZSH="$HOME/.local/share/oh-my-zsh"

if ! [ -d $ZSH ]; then
  git clone https://github.com/robbyrussell/oh-my-zsh.git $ZSH
fi

source $ZSH/oh-my-zsh.sh

source $HOME/dotfiles/zsh/rudolfs.zsh-theme
ZSH_THEME="rudolfs"

export EDITOR=nvim
# for GPG passphrase entry
export GPG_TTY=$(tty)

alias g='rg -i'
alias sl='ls'
alias v='nvim'
alias vim='nvim'
alias gco='git checkout'
alias pwg='printf "%s" $(pwgen -s 20 1) | tee >(pbcopy) | cat; echo'
alias find='fd'
alias df='duf'

# Git
alias gd='git diff'
alias gc='git commit -s -S'
alias gds='git diff --staged'
alias gst='git status'
alias gbd='git branch | cut -c 3- | fzy | xargs -p git branch -D'

gb() {
  if [ -n "$*" ]
  then
    git branch $*
  else
    git branch | cut -c 3- | fzy | xargs git checkout
  fi
}

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

[ -f $HOME/dotfiles/zsh/zshrc_local ] &&
  source $HOME/dotfiles/zsh/zshrc_local

. /opt/homebrew/opt/asdf/libexec/asdf.sh

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/opt/google-cloud-sdk/path.zsh.inc' ]; then . '/opt/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/opt/google-cloud-sdk/completion.zsh.inc' ]; then . '/opt/google-cloud-sdk/completion.zsh.inc'; fi
