export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

export HISTSIZE=10000000
export SAVEHIST=10000000
setopt share_history

autoload -Uz compinit && compinit
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'

export EDITOR=nvim
export GPG_TTY=$(tty)

alias ls='ls --color=auto'
alias sl='ls'
alias ll='ls -la'

alias g='rg -i'
alias v='nvim'
alias vim='nvim'
alias gco='git checkout'
alias find='fd'
alias df='duf'

# Git
alias gd='git diff'
alias gc='git commit'
alias gds='git diff --staged'
alias gst='git status'
alias gbd='git branch | cut -c 3- | fzy | xargs -p git branch -D'
alias gdm='git branch --merged | grep -E -v "(^\*|master|main)" | xargs git branch -d'

gb() {
  if [ -n "$*" ]
  then
    git branch $*
  else
    git branch | cut -c 3- | fzy | xargs git checkout
  fi
}

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

[ -f $HOME/dotfiles/zsh/zshrc_local ] &&
  source $HOME/dotfiles/zsh/zshrc_local

. /opt/homebrew/opt/asdf/libexec/asdf.sh

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/opt/google-cloud-sdk/path.zsh.inc' ]; then . '/opt/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/opt/google-cloud-sdk/completion.zsh.inc' ]; then . '/opt/google-cloud-sdk/completion.zsh.inc'; fi

eval "$(starship init zsh)"

# Set kitty tab title via starship
function set_win_title(){
    echo -ne "\033]0; $(basename "$PWD") \007"
}
precmd_functions+=(set_win_title)

# pnpm
export PNPM_HOME="/Users/rudolfs/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

# bun completions
[ -s "/Users/rudolfs/.bun/_bun" ] && source "/Users/rudolfs/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
source <(jj util completion zsh)

source /Users/rudolfs/.docker/init-zsh.sh || true # Added by Docker Desktop
# The following lines have been added by Docker Desktop to enable Docker CLI completions.
fpath=(/Users/rudolfs/.docker/completions $fpath)
autoload -Uz compinit
compinit
# End of Docker CLI completions

alias claude="/Users/rudolfs/.claude/local/claude"
